"use client"

import localFont from "next/font/local";
import "./globals.css";
import NavigationBar from "@/components/shared/NavigationBar/NavigationBar";
import Script from "next/script";
import FirebaseAuthProvider from "@/components/auth/FirebaseAuthProvider.jsx";
import Footer from "@/components/shared/Footer/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning >
      <FirebaseAuthProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <NavigationBar />
          {children}
          <Script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js" />
          {/* <Script src="../../node_modules/flowbite/dist/flowbite.js" /> */}
        </body>
        <Footer />
      </FirebaseAuthProvider>
    </html>
  );
}
